# Default values for java-builder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

git:
  Uri: https://github.com/nvnmandadhi/app1
  ref: main

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

contextDir: .
strategyType: s2i

imagePullSecrets: ["default"]
nameOverride: ""
sourceImage:
  type: DockerImage
  registry: harbor.apps.ocp.nmandadhi.com/library/s2i-jdk8:1.0

destImage:
  name: library/app1
  tag: "1.0"
  registry: harbor.apps.ocp.nmandadhi.com